const newsData = [
  {
    "id": "art-wa-1779687219236",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779687146497_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "25 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779687209701",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779687076210_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "25 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779680357932",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "Otomatik test yuklemesi",
    "content": "<p>Otomatik test yuklemesi</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779680357819_manual.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "25 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779643582016",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779643444776_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779642694232",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779642621468_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779642267743",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779642182204_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779642144261",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779642075674_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779641661196",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779641541323_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779641431645",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779641397006_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779640902936",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779640811106_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779640711694",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779640616582_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779640632182",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779640598018_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779637091353",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779637043110_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779636986499",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779636943162_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779604232796",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779604198351_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779604136120",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779604082784_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779603943909",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779603911779_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779603808562",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779603734661_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779603770887",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779603721729_wa.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779602315421",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "🤖 Antigravity Test Yayını #MersinManset #Test",
    "content": "<p>🤖 Antigravity Test Yayını #MersinManset #Test</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/1779602275344_manual.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779596267828",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gelen son görüntüler! Mersin sahil yolu bu sabah trafiğe kapatıldı.",
    "content": "<p>WhatsApp ihbar hattımıza gelen son görüntüler! Mersin sahil yolu bu sabah trafiğe kapatıldı.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/whatsapp_video_test_1779520360476.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779595809142",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gelen son görüntüler! Mersin sahil yolu bu sabah trafiğe kapatıldı.",
    "content": "<p>WhatsApp ihbar hattımıza gelen son görüntüler! Mersin sahil yolu bu sabah trafiğe kapatıldı.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/whatsapp_video_test_1779520360476.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "24 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779523641136",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gelen son görüntüler aşağıdadır.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/whatsapp_video_1779523641131.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "23 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779521082253",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gelen son görüntüler aşağıdadır.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/whatsapp_video_1779521082248.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "23 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-wa-1779520970124",
    "title": "WhatsApp İhbar Hattından Gelen Görüntüler",
    "excerpt": "WhatsApp ihbar hattımıza gönderilen son dakika görüntüleri.",
    "content": "<p>WhatsApp ihbar hattımıza gelen son görüntüler aşağıdadır.</p>\n<br>\n<video controls style=\"max-width: 100%; border-radius: 8px;\">\n  <source src=\"assets/whatsapp_video_1779520970118.mp4\" type=\"video/mp4\">\n  Tarayıcınız video etiketini desteklemiyor.\n</video>",
    "category": "dunya",
    "date": "23 Mayıs 2026",
    "author": "İzleyici İhbarı",
    "readTime": "1 dk izleme",
    "image": "assets/logo.png",
    "isFeatured": true,
    "isBreaking": true
  },
  {
    "id": "art-rss-1779437173400-7",
    "title": "İzmir'de vahşet. Çöp konteynerinin önünde 33 ölü kedi bulundu Gelişmeleri",
    "excerpt": "İzmir'in Buca ilçesinde bir çöp konteynerinin önünde 33 kedi ölü bulundu. Olayla ilgili soruşturma başlatıldı.",
    "content": "<p>İzmir'in Buca ilçesinde bir çöp konteynerinin önünde 33 kedi ölü bulundu.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Olayla ilgili soruşturma başlatıldı.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "22 Mayıs 2026",
    "author": "Kaan Demir",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/kedi-266367.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779437173400-6",
    "title": "CHP için mutlak butlan kararı | Mahkemenin kararı siyaseti ve ekonomiyi nasıl etkileyecek? 4 kritik etki! Gelişmeleri",
    "excerpt": "Türk siyasetinde ve Cumhuriyet Halk Partisi bünyesinde daha önce eşi benzeri görülmemiş, hafızalardan uzun süre silinmeyecek tarihi bir gece yaşandı! ...",
    "content": "<p>Türk siyasetinde ve Cumhuriyet Halk Partisi bünyesinde daha önce eşi benzeri görülmemiş, hafızalardan uzun süre silinmeyecek tarihi bir gece yaşandı.</p>\n\n<h3>Piyasalarda Kritik Beklentiler ve Analist Yorumları</h3>\n<p>Mahkemenin verdiği mutlak kutlan kritik karar adımıının ardından CHP Genel Merkezi adeta karıştı.</p>\n\n<blockquote>\n  \"Sıkı tedbirlerin ve piyasa disiplininin sürdürülmesi orta vadeli istikrarın teminatıdır.\"\n</blockquote>\n\n<p>kritik karar adımıı NTV siyaset yorumcusu Kemal Öztürk değerlendirdi.</p>\n\n",
    "category": "ekonomi",
    "date": "22 Mayıs 2026",
    "author": "Onur Koç",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/chp2-901261.jpg",
    "isFeatured": false,
    "isBreaking": true
  },
  {
    "id": "art-rss-1779437173400-5",
    "title": "AKOM gün gün paylaştı. Kurban Bayramı'nda hava nasıl olacak? Gelişmeleri",
    "excerpt": "Mayıs ayının bitmesine az bir süre kala serin ve yağışlı hava devam ediyor. Peki Kurban Bayramı'nda hava nasıl olacak, İstanbul'da bayramda yağmur var...",
    "content": "<p>Mayıs ayının bitmesine az bir süre kala serin ve yağışlı hava devam ediyor.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Peki Kurban Bayramı'nda hava nasıl olacak, İstanbul'da bayramda yağmur var mı.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "22 Mayıs 2026",
    "author": "Onur Koç",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/istanbul-yagmur-aa-1796320-868170.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779437173400-4",
    "title": "Yola çıkacaklar dikkat. Bayram tedbirleri kamuoyuyla resmen paylaşıldı \"Tuzak radar yok\" Gelişmeleri",
    "excerpt": "İçişleri Bakanı Mustafa Çiftçi, 9 günlük tatil süresince alınacak önlemleri açıkladı. Çiftçi, yoğun denetimlerin gerçekleştirileceğini, \"tuzak radar\"ı...",
    "content": "<p>İçişleri bakanlık yetkilisi Mustafa Çiftçi, 9 günlük tatil süresince alınacak önlemleri açıkladı.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Çiftçi, yoğun denetimlerin gerçekleştirileceğini, \"tuzak radar\"ın olmayacağını söyledi.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "22 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/RADARRR-375314.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779437172927-3",
    "title": "Küresel Sumud Filosu aktivistleri İstanbul'da Gelişmeleri",
    "excerpt": "Katil İsrail'in uluslararası sularda alıkoyduğu Küresel Sumud Filosu aktivistlerini taşıyan ve İsrail'den kalkan 3 uçak İstanbul'a geldi.",
    "content": "<p>Katil İsrail'in uluslararası sularda alıkoyduğu Küresel Sumud Filosu aktivistlerini taşıyan ve İsrail'den kalkan 3 uçak İstanbul'a geldi.</p>\n\n<h3>Geleceğin Dijital Altyapısı ve Güvenlik Parametreleri</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Yapay zeka ve uç bilişim entegrasyonu, veri egemenliğinin korunmasında en kritik aşamadır.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "teknoloji",
    "date": "22 Mayıs 2026",
    "author": "Selin Öztürk",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2462000/sumud-aktivist-aa-2463171.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779437172927-2",
    "title": "EFES2026 Tatbikatı başarıyla tamamlandı Gelişmeleri",
    "excerpt": "Türk Silahlı Kuvvetlerinin en büyük birleşik, müşterek tatbikatlarından EFES-2026 Tatbikatı, başarıyla tamamlandı.",
    "content": "<p>Türk Silahlı Kuvvetlerinin en meydana geldikça geniş çaplı birleşik, müşterek tatbikatlarından EFES-2026 Tatbikatı, başarıyla tamamlandı.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "22 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2462000/efes-tatbikat-2463053.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779437172927-1",
    "title": "Erdoğan: Türk ordusu barışın, huzurun ve istikrarın ordusudur Gelişmeleri",
    "excerpt": "Cumhurbaşkanı Recep Tayyip Erdoğan, \"Türk ordusu barışın ordusudur. Türk ordusu huzurun ordusudur. Türk ordusu istikrarın ordusudur. Dünyanın kendi or...",
    "content": "<p>Cumhurbaşkanı Recep Tayyip Erdoğan, \"Türk ordusu barışın ordusudur. Türk ordusu huzurun ordusudur.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Türk ordusu istikrarın ordusudur. küresel ölçeknın kendi ordusuna ithaf edilen tek milli marşı İstiklal Marşımızdır.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>'Hakkıdır, Hak'ka tapan milletimin istiklal' mısraında meydana geldiğu gibi Türk ordusu istiklalin ordusudur. \" ifadelerini kullandı.</p>\n\n",
    "category": "dunya",
    "date": "22 Mayıs 2026",
    "author": "Merve Yılmaz",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2462000/recep-tayyip-erdogan-2463170.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779437172922-0",
    "title": "Mahkeme CHP 38. Olağan Kurultayını iptal etti Gelişmeleri",
    "excerpt": "Ankara Bölge Adliye Mahkemesi (BAM) 36. Hukuk Dairesi, CHP kurultay davasında, Özgür Özel ile parti yönetiminin tedbiren görevden uzaklaştırılmasına, ...",
    "content": "<p>Ankara Bölge Adliye Mahkemesi (BAM) 36.</p>\n\n<h3>Geleceğin Dijital Altyapısı ve Güvenlik Parametreleri</h3>\n<p>Hukuk Dairesi, CHP kurultay davasında, Özgür Özel ile parti yönetiminin tedbiren görevden uzaklaştırılmasına, Kemal Kılıçdaroğlu ile yönetiminin görevi devralmasına kritik karar adımı verdi.</p>\n\n<blockquote>\n  \"Yapay zeka ve uç bilişim entegrasyonu, veri egemenliğinin korunmasında en kritik aşamadır.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "teknoloji",
    "date": "22 Mayıs 2026",
    "author": "Kaan Demir",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1516000/chp-genel-merkezi-1517945.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346684532-7",
    "title": "Resmi Gazete'de bugün (21 Mayıs 2026 Resmi Gazete kararları) Gelişmeleri",
    "excerpt": "Resmi Gazete'de 21 Mayıs 2026 tarihli kararlar, yönetmelikler ve tebliğler yayımlandı. Resmi Gazete'de bugün neler var? İşte 21 Mayıs 2026 tarihli ve ...",
    "content": "<p>Resmi Gazete'de 21 Mayıs 2026 tarihli kritik karar adımılar, yönetmelikler ve tebliğler yayımlandı.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Resmi Gazete'de bugün neler var.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>İşte 21 Mayıs 2026 tarihli ve 33260 Sayılı Resmi Gazete ayrıntıları.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Zeynep Yıldız",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/thumbs_b_c_d6a254b33abdc49866289-774765.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346684532-6",
    "title": "Bir anda bastıran yağmur yolları ve tünelleri göle çevirdi. Kuvvetli sağanak geliyor, İstanbul için saat verildi Gelişmeleri",
    "excerpt": "Meteoroloji Genel Müdürlüğü (MGM) ve AKOM'un uyarılarının ardından İstanbul'da sabah saatlerinde çok kuvvetli sağanak etkili oldu. Sağanak nedeniyle y...",
    "content": "<p>Meteoroloji Genel Müdürlüğü (MGM) ve AKOM'un uyarılarının ardından İstanbul'da sabah saatlerinde çok kuvvetli sağanak etkili meydana geldi.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Sağanak nedeniyle yollar ve tüneller sular altında kalırken kentte gökkuşağı da oluştu.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Öte yandan MGM, saat vererek kuvvetli sağanağa karşı uyardı.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Burak Çelik",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/MALTEPE’DE-TUNELI-SU-BASTI-ARACLAR-ILER_1323485_393154-395521.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346684532-5",
    "title": "Sağanak nedeniyle çöken evdeki 1 kişi hayatını kaybetti Gelişmeleri",
    "excerpt": "Hatay'ın merkez Antakya ilçesinde sağanak nedeniyle çöken evdeki 1 kişi yaşamını yitirdi.",
    "content": "<p>Hatay'ın merkez Antakya ilçesinde sağanak nedeniyle çöken evdeki 1 kişi yaşamını yitirdi.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/6982ec5d1e3acb8660856999285b7497-884419.png",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346684532-4",
    "title": "Rasim Ozan Kütahyalı'nın cezaevi değiştirildi Gelişmeleri",
    "excerpt": "Yasa dışı bahis soruşturmasında tutuklanan Rasim Ozan Kütahyalı, Adana Kürkçüler E Tipi Cezaevi'nden İstanbul Maltepe Cezaevi'ne nakli gerçekleştirild...",
    "content": "<p>Yasa dışı bahis soruşturmasında tutuklanan Rasim Ozan Kütahyalı, Adana Kürkçüler E Tipi Cezaevi'nden İstanbul Maltepe Cezaevi'ne nakli gerçekleştirildi.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Arda Şahin",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/AA-20260517-41408295-41408281-ADANA_MERKEZLI_YASA_DISI_BAHIS_OPERASYONUNDA_YAKALANAN_154_ZANLI_ADLIYEDE-497941.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346683896-3",
    "title": "Haydut İsrail'e dünyadan tepki: İsrailli diplomatlardan izahat istendi Gelişmeleri",
    "excerpt": "Haydut İsrail tarafından uluslararası sularda alıkonulan Küresel Sumud Filosu aktivistlerine yönelik insanlık dışı muameleye dünyadan tepkiler geldi.",
    "content": "<p>Haydut İsrail tarafından uluslararası sularda alıkonulan Küresel Sumud Filosu aktivistlerine yönelik insanlık dışı muameleye küresel ölçekdan tepkiler geldi.</p>\n\n<h3>Geleceğin Dijital Altyapısı ve Güvenlik Parametreleri</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Yapay zeka ve uç bilişim entegrasyonu, veri egemenliğinin korunmasında en kritik aşamadır.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "teknoloji",
    "date": "21 Mayıs 2026",
    "author": "Burak Çelik",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2450000/sumud-in-marseilles-a-2451215.jpg",
    "isFeatured": false,
    "isBreaking": true
  },
  {
    "id": "art-rss-1779346683896-2",
    "title": "Türkiye'den haydut İsrail'in Sumud aktivistlerine saldırısına sert tepki Gelişmeleri",
    "excerpt": "Dışişleri Bakanlığı, İsrailli bir bakanın, İsrail tarafından alıkonulan Küresel Sumud Filosu katılımcılarına yönelik sözlü ve fiziki şiddet uygulaması...",
    "content": "<p>Dışişleri Bakanlığı, İsrailli bir bakanlık yetkilisin, İsrail tarafından alıkonulan Küresel Sumud Filosu katılımcılarına yönelik sözlü ve fiziki şiddet uygulamasını lanetledi.</p>\n\n<h3>Geleceğin Dijital Altyapısı ve Güvenlik Parametreleri</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Yapay zeka ve uç bilişim entegrasyonu, veri egemenliğinin korunmasında en kritik aşamadır.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "teknoloji",
    "date": "21 Mayıs 2026",
    "author": "Onur Koç",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1760000/disisleri-bakanligi-depo-1761807.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346683896-1",
    "title": "Türkiye'nin caydırıcı gücünde tarihi adım Gelişmeleri",
    "excerpt": "Türkiye'nin yerli ve milli imkanlarla geliştirdiği uzun menzilli füze sistemi TAYFUN’un Blok-2 versiyonunun teslimatı gerçekleştirilerek Türk Silahlı ...",
    "content": "<p>ülkemiz genelinde'nin yerli ve milli imkanlarla geliştirdiği uzun menzilli füze sistemi TAYFUN’un Blok-2 versiyonunun teslimatı gerçekleştirilerek Türk Silahlı Kuvvetleri (TSK) envanterine dahil edildi.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Selin Öztürk",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2410000/haluk-gorgun-tayfun-2411194.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346683896-0",
    "title": "DSÖ'den Ebola uyarısı: Aşı çalışmaları dokuz ay kadar sürebilir Gelişmeleri",
    "excerpt": "Dünya Sağlık Örgütü (DSÖ), Demokratik Kongo Cumhuriyeti'nde (DKC) yayılım gösteren nadir bir Ebola türüne karşı geliştirilmekte olan aşının hazır hale...",
    "content": "<p>küresel ölçek Sağlık Örgütü (DSÖ), Demokratik Kongo Cumhuriyeti'nde (DKC) yayılım gösteren nadir bir Ebola türüne karşı geliştirilmekte olan aşının hazır hale gelmesinin dokuz ayı bulabileceğini açıkladı.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1522000/ebola-asisi-reuters-1522939.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346582289-3",
    "title": "Dorukhan oldukça geniş çaplıışık dosyası kapsamında 26 şüpheli hakkında gözaltı kararı Gelişmeleri",
    "excerpt": "Adalet Bakanı Akın Gürlek, Dorukhan Büyükışık dosyasında ortaya çıkan yeni deliller, bilirkişi raporları, teknik incelemeler, HTS ve daraltılmış baz k...",
    "content": "<p>Adalet bakanlık yetkilisi Akın Gürlek, Dorukhan meydana geldikça geniş çaplıışık dosyasında ortaya çıkan yeni nesil deliller, bilirkişi raporları, teknik incelemeler, HTS ve daraltılmış baz kayıtları ile delillerin kritik karar adımıtıldığına yönelik bulgular ışığında 26 şüpheli hakkında gözaltı kritik karar adımıının verildiğini, İzmir merkezli 9 ilde bu sabah eş zamanlı operasyon başlatıldığını belirtti.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2108000/kayseri-cinayet-2108135.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346582289-2",
    "title": "Hatay'da sağanak sele dönüştü: Köprü çöktü, göçük meydana geldi Gelişmeleri",
    "excerpt": "Hatay'da sağanak nedeniyle bazı cadde ve sokaklarda su birikintileri oluştu. Antakya ilçesinde sağanak nedeniyle çöken evdeki 1 kişi yaşamını yitirdi....",
    "content": "<p>Hatay'da sağanak nedeniyle bazı cadde ve sokaklarda su birikintileri oluştu.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Antakya ilçesinde sağanak nedeniyle çöken evdeki 1 kişi yaşamını yitirdi.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Samandağ ilçesinde ise köprü yıkıldı.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2462000/hatay-saganak-aa-2462729.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346582289-1",
    "title": "Cumhurbaşkanı Erdoğan, ABD Başkanı Trump ile görüştü Gelişmeleri",
    "excerpt": "Cumhurbaşkanı Recep Tayyip Erdoğan, ABD Başkanı Donald Trump ile telefonda görüştü.",
    "content": "<p>Cumhurbaşkanı Recep Tayyip Erdoğan, ABD Başkanı Donald Trump ile telefonda görüştü.</p>\n\n<h3>Geleceğin Dijital Altyapısı ve Güvenlik Parametreleri</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Yapay zeka ve uç bilişim entegrasyonu, veri egemenliğinin korunmasında en kritik aşamadır.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "teknoloji",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2452000/erdogan-trump-2452351.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346582285-0",
    "title": "Ünlü isimlere uyuşturucu operasyonu: 14 gözaltı Gelişmeleri",
    "excerpt": "İstanbul'da ünlülere yönelik düzenlenen uyuşturucu operasyonunda Serenay Sarıkaya, Tan Taşcı, Berkay Şahin, Fatih Karaca (Mabel Matiz), Hakan Aydın (B...",
    "content": "<p>İstanbul'da ünlülere yönelik düzenlenen uyuşturucu operasyonunda Serenay Sarıkaya, Tan Taşcı, Berkay Şahin, Fatih Karaca (Mabel Matiz), Hakan Aydın (Blok3), Feyza Civelek, Volkan Bahçekapalı ve Onur Tuna'nın da aralarında bulunduğu 14 kişi gözaltına alındı.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Burak Çelik",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1752000/gozalti-stok-1752516.jpg",
    "isFeatured": true,
    "isBreaking": false
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = newsData;
}