const newsData = [
  {
    "id": "art-rss-1779346684532-7",
    "title": "Resmi Gazete'de bugün (21 Mayıs 2026 Resmi Gazete kararları) Gelişmeleri",
    "excerpt": "Resmi Gazete'de 21 Mayıs 2026 tarihli kararlar, yönetmelikler ve tebliğler yayımlandı. Resmi Gazete'de bugün neler var? İşte 21 Mayıs 2026 tarihli ve ...",
    "content": "<p>Resmi Gazete'de 21 Mayıs 2026 tarihli kritik karar adımılar, yönetmelikler ve tebliğler yayımlandı.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Resmi Gazete'de bugün neler var.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>İşte 21 Mayıs 2026 tarihli ve 33260 Sayılı Resmi Gazete ayrıntıları.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Zeynep Yıldız",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/thumbs_b_c_d6a254b33abdc49866289-774765.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346684532-6",
    "title": "Bir anda bastıran yağmur yolları ve tünelleri göle çevirdi. Kuvvetli sağanak geliyor, İstanbul için saat verildi Gelişmeleri",
    "excerpt": "Meteoroloji Genel Müdürlüğü (MGM) ve AKOM'un uyarılarının ardından İstanbul'da sabah saatlerinde çok kuvvetli sağanak etkili oldu. Sağanak nedeniyle y...",
    "content": "<p>Meteoroloji Genel Müdürlüğü (MGM) ve AKOM'un uyarılarının ardından İstanbul'da sabah saatlerinde çok kuvvetli sağanak etkili meydana geldi.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Sağanak nedeniyle yollar ve tüneller sular altında kalırken kentte gökkuşağı da oluştu.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Öte yandan MGM, saat vererek kuvvetli sağanağa karşı uyardı.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Burak Çelik",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/MALTEPE’DE-TUNELI-SU-BASTI-ARACLAR-ILER_1323485_393154-395521.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346684532-5",
    "title": "Sağanak nedeniyle çöken evdeki 1 kişi hayatını kaybetti Gelişmeleri",
    "excerpt": "Hatay'ın merkez Antakya ilçesinde sağanak nedeniyle çöken evdeki 1 kişi yaşamını yitirdi.",
    "content": "<p>Hatay'ın merkez Antakya ilçesinde sağanak nedeniyle çöken evdeki 1 kişi yaşamını yitirdi.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/6982ec5d1e3acb8660856999285b7497-884419.png",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346684532-4",
    "title": "Rasim Ozan Kütahyalı'nın cezaevi değiştirildi Gelişmeleri",
    "excerpt": "Yasa dışı bahis soruşturmasında tutuklanan Rasim Ozan Kütahyalı, Adana Kürkçüler E Tipi Cezaevi'nden İstanbul Maltepe Cezaevi'ne nakli gerçekleştirild...",
    "content": "<p>Yasa dışı bahis soruşturmasında tutuklanan Rasim Ozan Kütahyalı, Adana Kürkçüler E Tipi Cezaevi'nden İstanbul Maltepe Cezaevi'ne nakli gerçekleştirildi.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Arda Şahin",
    "readTime": "1 dk okuma",
    "image": "https://images.ntv.com.tr/images/AA-20260517-41408295-41408281-ADANA_MERKEZLI_YASA_DISI_BAHIS_OPERASYONUNDA_YAKALANAN_154_ZANLI_ADLIYEDE-497941.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346683896-3",
    "title": "Haydut İsrail'e dünyadan tepki: İsrailli diplomatlardan izahat istendi Gelişmeleri",
    "excerpt": "Haydut İsrail tarafından uluslararası sularda alıkonulan Küresel Sumud Filosu aktivistlerine yönelik insanlık dışı muameleye dünyadan tepkiler geldi.",
    "content": "<p>Haydut İsrail tarafından uluslararası sularda alıkonulan Küresel Sumud Filosu aktivistlerine yönelik insanlık dışı muameleye küresel ölçekdan tepkiler geldi.</p>\n\n<h3>Geleceğin Dijital Altyapısı ve Güvenlik Parametreleri</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Yapay zeka ve uç bilişim entegrasyonu, veri egemenliğinin korunmasında en kritik aşamadır.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "teknoloji",
    "date": "21 Mayıs 2026",
    "author": "Burak Çelik",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2450000/sumud-in-marseilles-a-2451215.jpg",
    "isFeatured": false,
    "isBreaking": true
  },
  {
    "id": "art-rss-1779346683896-2",
    "title": "Türkiye'den haydut İsrail'in Sumud aktivistlerine saldırısına sert tepki Gelişmeleri",
    "excerpt": "Dışişleri Bakanlığı, İsrailli bir bakanın, İsrail tarafından alıkonulan Küresel Sumud Filosu katılımcılarına yönelik sözlü ve fiziki şiddet uygulaması...",
    "content": "<p>Dışişleri Bakanlığı, İsrailli bir bakanlık yetkilisin, İsrail tarafından alıkonulan Küresel Sumud Filosu katılımcılarına yönelik sözlü ve fiziki şiddet uygulamasını lanetledi.</p>\n\n<h3>Geleceğin Dijital Altyapısı ve Güvenlik Parametreleri</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Yapay zeka ve uç bilişim entegrasyonu, veri egemenliğinin korunmasında en kritik aşamadır.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "teknoloji",
    "date": "21 Mayıs 2026",
    "author": "Onur Koç",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1760000/disisleri-bakanligi-depo-1761807.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346683896-1",
    "title": "Türkiye'nin caydırıcı gücünde tarihi adım Gelişmeleri",
    "excerpt": "Türkiye'nin yerli ve milli imkanlarla geliştirdiği uzun menzilli füze sistemi TAYFUN’un Blok-2 versiyonunun teslimatı gerçekleştirilerek Türk Silahlı ...",
    "content": "<p>ülkemiz genelinde'nin yerli ve milli imkanlarla geliştirdiği uzun menzilli füze sistemi TAYFUN’un Blok-2 versiyonunun teslimatı gerçekleştirilerek Türk Silahlı Kuvvetleri (TSK) envanterine dahil edildi.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Selin Öztürk",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2410000/haluk-gorgun-tayfun-2411194.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346683896-0",
    "title": "DSÖ'den Ebola uyarısı: Aşı çalışmaları dokuz ay kadar sürebilir Gelişmeleri",
    "excerpt": "Dünya Sağlık Örgütü (DSÖ), Demokratik Kongo Cumhuriyeti'nde (DKC) yayılım gösteren nadir bir Ebola türüne karşı geliştirilmekte olan aşının hazır hale...",
    "content": "<p>küresel ölçek Sağlık Örgütü (DSÖ), Demokratik Kongo Cumhuriyeti'nde (DKC) yayılım gösteren nadir bir Ebola türüne karşı geliştirilmekte olan aşının hazır hale gelmesinin dokuz ayı bulabileceğini açıkladı.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1522000/ebola-asisi-reuters-1522939.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346582289-3",
    "title": "Dorukhan oldukça geniş çaplıışık dosyası kapsamında 26 şüpheli hakkında gözaltı kararı Gelişmeleri",
    "excerpt": "Adalet Bakanı Akın Gürlek, Dorukhan Büyükışık dosyasında ortaya çıkan yeni deliller, bilirkişi raporları, teknik incelemeler, HTS ve daraltılmış baz k...",
    "content": "<p>Adalet bakanlık yetkilisi Akın Gürlek, Dorukhan meydana geldikça geniş çaplıışık dosyasında ortaya çıkan yeni nesil deliller, bilirkişi raporları, teknik incelemeler, HTS ve daraltılmış baz kayıtları ile delillerin kritik karar adımıtıldığına yönelik bulgular ışığında 26 şüpheli hakkında gözaltı kritik karar adımıının verildiğini, İzmir merkezli 9 ilde bu sabah eş zamanlı operasyon başlatıldığını belirtti.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2108000/kayseri-cinayet-2108135.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346582289-2",
    "title": "Hatay'da sağanak sele dönüştü: Köprü çöktü, göçük meydana geldi Gelişmeleri",
    "excerpt": "Hatay'da sağanak nedeniyle bazı cadde ve sokaklarda su birikintileri oluştu. Antakya ilçesinde sağanak nedeniyle çöken evdeki 1 kişi yaşamını yitirdi....",
    "content": "<p>Hatay'da sağanak nedeniyle bazı cadde ve sokaklarda su birikintileri oluştu.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Antakya ilçesinde sağanak nedeniyle çöken evdeki 1 kişi yaşamını yitirdi.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Samandağ ilçesinde ise köprü yıkıldı.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2462000/hatay-saganak-aa-2462729.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346582289-1",
    "title": "Cumhurbaşkanı Erdoğan, ABD Başkanı Trump ile görüştü Gelişmeleri",
    "excerpt": "Cumhurbaşkanı Recep Tayyip Erdoğan, ABD Başkanı Donald Trump ile telefonda görüştü.",
    "content": "<p>Cumhurbaşkanı Recep Tayyip Erdoğan, ABD Başkanı Donald Trump ile telefonda görüştü.</p>\n\n<h3>Geleceğin Dijital Altyapısı ve Güvenlik Parametreleri</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Yapay zeka ve uç bilişim entegrasyonu, veri egemenliğinin korunmasında en kritik aşamadır.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "teknoloji",
    "date": "21 Mayıs 2026",
    "author": "Elif Kaya",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/2452000/erdogan-trump-2452351.jpg",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-rss-1779346582285-0",
    "title": "Ünlü isimlere uyuşturucu operasyonu: 14 gözaltı Gelişmeleri",
    "excerpt": "İstanbul'da ünlülere yönelik düzenlenen uyuşturucu operasyonunda Serenay Sarıkaya, Tan Taşcı, Berkay Şahin, Fatih Karaca (Mabel Matiz), Hakan Aydın (B...",
    "content": "<p>İstanbul'da ünlülere yönelik düzenlenen uyuşturucu operasyonunda Serenay Sarıkaya, Tan Taşcı, Berkay Şahin, Fatih Karaca (Mabel Matiz), Hakan Aydın (Blok3), Feyza Civelek, Volkan Bahçekapalı ve Onur Tuna'nın da aralarında bulunduğu 14 kişi gözaltına alındı.</p>\n\n<h3>Küresel Ölçekte Diplomatik ve Siyasi Yansımaları</h3>\n<p>Söz konusu gelişmelerin sektörel bazda yaratacağı etkiler ve gelecek döneme ilişkin makro göstergeler analistler tarafından incelenmeye devam ediliyor.</p>\n\n<blockquote>\n  \"Küresel diplomasi kanallarının açık tutulması, bölgesel istikrarın ve barışın sürdürülebilirliği için elzemdir.\"\n</blockquote>\n\n<p>Gelişmelerin seyri doğrultusunda yaşanacak yeni gelişmeleri ve resmi kurumların yapacağı açıklamaları anlık olarak aktarmaya devam edeceğiz.</p>\n\n",
    "category": "dunya",
    "date": "21 Mayıs 2026",
    "author": "Burak Çelik",
    "readTime": "1 dk okuma",
    "image": "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1752000/gozalti-stok-1752516.jpg",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-1-tech",
    "title": "Nesnelerin Zekası: Edge AI ve Çoklu Ajan Sistemleri ile Yeni Bilişim Devrimi",
    "excerpt": "Bulut bilişimin sınırlarını aşan Edge AI (Uç Yapay Zeka) ve işbirlikçi çoklu ajan sistemleri, 2026 yılında akıllı cihazları bağımsız birer karar merciine dönüştürüyor.",
    "content": "\n      <p>Bilgi teknolojileri dünyası, merkezi bulut sunucularının veri işleme tekelini kıran yeni bir mimari dalganın etkisinde. 2026 yılı itibarıyla hız kazanan Edge AI (Uç Yapay Zeka) ve otonom karar alabilen çoklu ajan (multi-agent) sistemlerinin entegrasyonu, veri iletişimindeki gecikme sürelerini sıfıra indirirken veri güvenliğini de yerel düzeyde maksimuma çıkarıyor.</p>\n      \n      <p>Geleneksel yapay zeka modelleri, milyarlarca parametrelik veri setlerini işlemek için büyük veri merkezlerine ihtiyaç duyuyordu. Ancak, uç bilişim donanımlarının ve mikrosaniyeler mertebesinde çalışan sinirsel işlem birimlerinin (NPU) yaygınlaşmasıyla, artık cebimizdeki telefonlardan otonom araçlara kadar her cihaz kendi kararlarını yerinde üretebiliyor.</p>\n      \n      <h3>Çoklu Ajan Mimarisi: Birlikte Çalışan Zekalar</h3>\n      <p>Çoklu ajan sistemleri, tek bir devasa yapay zeka yerine, belirli alanlarda uzmanlaşmış küçük ajanların bir protokol dahilinde iletişim kurarak karmaşık problemleri çözmesini temel alıyor. Örneğin akıllı şehir altyapısında; trafik lambalarını kontrol eden ajan, ambulansın konumunu takip eden ajan ve hava kalitesini ölçen ajan eşzamanlı olarak bilgi alışverişi yaparak anlık kararlar alıyor.</p>\n      \n      <blockquote>\n        \"Edge AI ve çoklu ajan işbirlikleri, internet bağlantısının olmadığı veya kısıtlı olduğu koşullarda dahi sistemlerin kesintisiz ve akıllı kararlar alabilmesini mümkün kılıyor. Bu, dijital ekosistemde tam bağımsızlığın ilk adımıdır.\"\n      </blockquote>\n      \n      <p>Bu devrimin en somut yansımaları endüstriyel üretim hatlarında görülüyor. Otonom robotlar, bulut sunucularına bağlanmadan kendi aralarında yaptıkları yerel kablosuz haberleşmeyle üretim sırasındaki mekanik hataları saniyeler içinde tespit edip düzeltebiliyor. 2026 ve sonrasında, akıllı ev sistemlerinden sağlık cihazlarına kadar tüm tüketici elektroniği ürünlerinin bu akıllı işbirliği mimarisiyle donatılması bekleniyor.</p>\n    ",
    "category": "teknoloji",
    "date": "21 Mayıs 2026",
    "author": "Can Tekin",
    "readTime": "5 dk okuma",
    "image": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-2-econ",
    "title": "Küresel Kriz Kıskacında TCMB Para Politikası: 2026 Yıl Sonu Enflasyon Beklentileri ve Faiz Kararlılığı",
    "excerpt": "Türkiye Cumhuriyet Merkez Bankası (TCMB), 2026 yılı Mayıs ayı PPK toplantısında politika faizini yüzde 37 seviyesinde sabit tutarken yıl sonu enflasyon hedeflerinde kararlı duruşunu yineledi.",
    "content": "\n      <p>Küresel piyasalarda enerji fiyatlarındaki dalgalanmalar ve jeopolitik risklerin tırmanışı sürerken, Türkiye Cumhuriyet Merkez Bankası (TCMB) Para Politikası Kurulu (PPK), Mayıs 2026 kararlarını açıkladı. Kurul, piyasa beklentileriyle paralel bir şekilde politika faizini yüzde 37 düzeyinde sabit tuttu. Karar metninde, enflasyondaki düşüş eğiliminin kalıcı hale getirilmesi için sıkı duruşun kararlılıkla sürdürüleceği vurgulandı.</p>\n      \n      <p>Merkez Bankası Başkanı, gerçekleştirdiği basın toplantısında küresel likidite koşullarına ve iç talep dengelenmesine yönelik önemli açıklamalarda bulundu. Yıl sonu enflasyon tahminlerinin yüzde 26 bandında tutulması için parasal aktarım mekanizmasının tüm araçlarla destekleneceği, gerekirse ek sıkılaşma adımlarının atılmaktan çekinilmeyeceği ifade edildi.</p>\n      \n      <h3>Ekonomistlerin Değerlendirmeleri ve Piyasa Yansımaları</h3>\n      <p>Finansal analizciler, TCMB'nin faiz sabit tutma kararının piyasalarda istikrarı korumaya yönelik doğru bir hamle olduğunu savunuyor. Özellikle döviz kurlarındaki göreceli sakin seyir ve dış ticaret dengesindeki iyileşme, Merkez Bankası'nın elini güçlendiren temel faktörler arasında yer alıyor.</p>\n      \n      <blockquote>\n        \"Sıkı para politikası ve seçici kredi sınırlamaları iç talebi dengelerken, reel sektörün finansman maliyetlerini de yakından etkiliyor. 2026'nın ikinci yarısında enflasyondaki baz etkisiyle birlikte düşüşün hızlanması beklenebilir.\"\n      </blockquote>\n      \n      <p>Karar sonrasında Borsa İstanbul 100 endeksi (BIST 100) pozitif bir seyir izlerken, tahvil faizlerinde ve ülke risk priminde (CDS) gerileme kaydedildi. Yatırımcılar, enflasyonla mücadele programının orta vadeli hedeflerine uyumunu yakından izlemeyi sürdürüyor.</p>\n    ",
    "category": "ekonomi",
    "date": "21 Mayıs 2026",
    "author": "Selim Yılmaz",
    "readTime": "4 dk okuma",
    "image": "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=1200&q=80",
    "isFeatured": false,
    "isBreaking": true
  },
  {
    "id": "art-3-sci",
    "title": "Nörolojik Hastalıklarda Hücresel Kalkan: Alzheimer ve Parkinson Tedavisinde Yeni Hücre Keşfi",
    "excerpt": "Uluslararası nörobilim ekibi, insan beyninde Alzheimer ve Parkinson gibi dejeneratif hastalıkların ilerlemesini durdurabilen özel bir mikroglia alt türü keşfetti.",
    "content": "\n      <p>Tıp dünyası, milyonlarca insanı ve ailelerini etkileyen Alzheimer, Parkinson ve ALS gibi nörodejeneratif hastalıkların tedavisinde çığır açabilecek tarihi bir bilimsel keşfe tanıklık ediyor. Yapılan araştırmalarda, insan beyninde yaşlanma ve hücresel stres dönemlerinde aktifleşen ve sinir hücrelerini koruyan özel bir bağışıklık hücresi (mikroglia) alt grubu tespit edildi.</p>\n      \n      <p>Nature Medicine dergisinde yayımlanan çalışmaya göre, bu özel hücreler beyinde biriken zararlı protein plaklarını (amiloid beta ve alfa-sinüklein) henüz oluşum aşamasındayken yutarak temizliyor. Bu süreç, hastalıkların erken aşamalarda teşhis edilmesi durumunda ilerlemesinin tamamen durdurulabileceğini gösteriyor.</p>\n      \n      <h3>Hücresel Kalkanı Aktifleştiren Gen Terapileri</h3>\n      <p>Araştırmanın Türkiye ayağını yürüten moleküler biyoloji uzmanları, bu koruyucu mikroglia hücrelerini yapay olarak uyarabilen spesifik bir genetik kod sentezlemeyi başardı. Laboratuvar ortamındaki ilk denemeler, beynin kendi savunma mekanizmasını harekete geçirerek harabiyeti durdurabildiğini kanıtladı.</p>\n      \n      <blockquote>\n        \"Beynin kendi içindeki bu gizli koruyucu kalkanı keşfetmek, dışarıdan kimyasal ilaç vermeye gerek kalmadan hastalıkları hücresel boyutta yenmemizin yolunu açıyor. Bu, nörolojide yeni bir çağdır.\"\n      </blockquote>\n      \n      <p>Araştırmacılar, önümüzdeki aylarda klinik deney fazlarına geçileceğini ve 2026 yılı sonuna kadar hedeflenmiş bağışıklık terapilerinin ilk hasta gruplarında uygulanmaya başlanacağını belirtiyor. Bu gelişme, nörodejeneratif hastalıkların kaderini sonsuza dek değiştirebilir.</p>\n    ",
    "category": "bilim",
    "date": "20 Mayıs 2026",
    "author": "Dr. Aylin Kurt",
    "readTime": "6 dk okuma",
    "image": "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?auto=format&fit=crop&w=1200&q=80",
    "isFeatured": true,
    "isBreaking": false
  },
  {
    "id": "art-4-world",
    "title": "Enerji Koridorlarında Deprem: Hürmüz Boğazı Gerilimi ve 100 Dolar Eşiğindeki Brent Petrol",
    "excerpt": "Hürmüz Boğazı'nda yükselen jeopolitik riskler, küresel ham petrol arzına ilişkin endişeleri tetikleyerek Brent petrolün varil fiyatını son iki yılın zirvesi olan 98 dolara taşıdı.",
    "content": "\n      <p>Orta Doğu'nun en kritik deniz geçiş noktalarından biri olan Hürmüz Boğazı'nda ticari gemilere yönelik tacizler ve artan bölgesel gerilimler, küresel enerji piyasalarında adeta deprem etkisi yarattı. Dünya petrol sevkiyatının yaklaşık yüzde 20'sinin geçtiği bu kritik boğazdaki geçiş güvenliği endişeleri nedeniyle, Brent petrolün varil fiyatı hızla yükselerek 100 dolar sınırına dayandı.</p>\n      \n      <p>Uluslararası Enerji Ajansı (IEA), arz güvenliğine yönelik risklerin sürmesi halinde stratejik petrol rezervlerinin devreye sokulabileceğini açıkladı. Ancak uzmanlar, boğazın tamamen veya kısmen kapanması senaryosunun küresel tedarik zincirinde telafisi zor aksamalara yol açabileceğini belirtiyor.</p>\n      \n      <h3>Enflasyonist Baskı ve Alternatif Rotalar</h3>\n      <p>Petrol fiyatlarındaki bu ani yükseliş, batılı ülkelerde henüz yeni kontrol altına alınmaya başlanan enflasyonu yeniden körükleme riski taşıyor. Akaryakıt maliyetlerindeki artışın, lojistik ve gıda fiyatları üzerinden tüm tüketici fiyatlarına yansıması kaçınılmaz görünüyor. Küresel lojistik devleri ise şimdiden Ümit Burnu üzerinden geçen daha uzun ve maliyetli alternatif rotaları kullanmaya başladı.</p>\n      \n      <blockquote>\n        \"Hürmüz Boğazı sadece fiziki bir geçiş noktası değil, küresel ekonominin can damarıdır. Buradaki en ufak bir tıkanıklık, Tokyo'dan New York'a kadar her bakkal rafında hissedilir.\"\n      </blockquote>\n      \n      <p>Analistler, jeopolitik gerginliğin diplomatik yollarla çözülememesi durumunda, yaz aylarında Brent petrolün 110 dolar seviyelerini görebileceği uyarısında bulunuyor. Bu durum, yenilenebilir enerjiye geçiş süreçlerinin neden daha da hızlandırılması gerektiğini bir kez daha gözler önüne seriyor.</p>\n    ",
    "category": "dunya",
    "date": "20 Mayıs 2026",
    "author": "Hakan Şen",
    "readTime": "4 dk okuma",
    "image": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1200&q=80",
    "isFeatured": false,
    "isBreaking": false
  },
  {
    "id": "art-5-cult",
    "title": "Teknolojik Estetik: SAHA 2026 Fuarında Otonom Sistemlerin Endüstriyel Tasarım Devrimi",
    "excerpt": "İstanbul'da düzenlenen SAHA 2026 Savunma ve Havacılık Fuarı, sadece askeri kabiliyetleriyle değil, otonom araçların fütüristik endüstriyel tasarımlarıyla da kültürel bir estetik tartışması başlattı.",
    "content": "\n      <p>Teknolojinin gelişi, insanoğlunun estetik algısını da baştan aşağı değiştiriyor. İstanbul Fuar Merkezi'nde kapılarını açan SAHA 2026 Savunma, Havacılık ve Uzay Sanayi Fuarı, sergilenen yeni nesil insansız hava, kara ve deniz araçlarıyla sadece mühendislik başarısını değil, endüstriyel tasarımın ulaştığı sanatsal olgunluğu da gözler önüne serdi.</p>\n      \n      <p>Klasik askeri araçların köşeli ve kaba tasarımları, yerini aerodinamik olarak optimize edilmiş, pürüzsüz organik formlara bırakıyor. Yapay zekanın tasarım süreçlerine dahil edilmesiyle geliştirilen fütüristik çizgiler, araçlara adeta yaşayan birer organizma görüntüsü kazandırıyor. Bu durum, savunma sanayisini sadece bir mühendislik alanı olmaktan çıkarıp endüstriyel sanatın sergilendiği bir arenaya dönüştürüyor.</p>\n      \n      <h3>İnsan-Makine Arayüzünde Minimalizm</h3>\n      <p>Fuarın en çok ilgi gören tasarımlarından biri de otonom kara araçlarının kontrol üniteleri oldu. Kullanıcı dostu arayüzler ve minimal kokpit tasarımları, karmaşık ekran kalabalığını ortadan kaldırarak operatörlerin dikkatini en üst düzeyde tutmayı hedefliyor. Kültür ve sanat eleştirmenleri, bu minimalist fütüristik yaklaşımın modern mimari ve otomotiv sektörünü de derinden etkileyeceğini belirtiyor.</p>\n      \n      <blockquote>\n        \"Otonom araçların tasarımı, işlevsellik ile dijital sanatın mükemmel bir sentezidir. SAHA 2026'da gördüğümüz çizgiler, önümüzdeki 10 yılın genel tasarım dilini şimdiden tanımlıyor.\"\n      </blockquote>\n      \n      <p>Ziyaretçilerin yoğun ilgisiyle devam eden fuar, otonom sistemlerin sadece askeri stratejileri değil, gündelik yaşamımızdaki estetik ve tasarım vizyonunu da nasıl şekillendirdiğini gösteren benzersiz bir kültür platformu haline gelmiş durumda.</p>\n    ",
    "category": "kultur",
    "date": "19 Mayıs 2026",
    "author": "Elif Demir",
    "readTime": "4 dk okuma",
    "image": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
    "isFeatured": false,
    "isBreaking": false
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = newsData;
}
